sudo: required
services:
  - docker


before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react  npm run test


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-360109119318"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
